foreground = yes
pid =
debug = notice
syslog = yes

[trace]
client = yes
accept = /run/rh-fullnode-trace/trace.sock
connect = 100.76.129.27:19445
cert = /etc/rh-storage-delta/tls/own-cert.pem
key = /etc/rh-storage-delta/tls/own-key.pem
CAfile = /etc/rh-storage-delta/tls/peer-trust.pem
verifyChain = yes
verifyPeer = yes
requireCert = yes
sslVersionMin = TLSv1.3
TIMEOUTconnect = 5
TIMEOUTbusy = 30
TIMEOUTidle = 60
TIMEOUTclose = 5
