[Unit]
After=tailscaled.service rh-trace-proxy.service
Wants=tailscaled.service rh-trace-proxy.service

[Service]
User=ec2-user
Group=ec2-user
RuntimeDirectoryMode=0700
CapabilityBoundingSet=
AmbientCapabilities=
RestrictSUIDSGID=true
ReadOnlyPaths=/run/rh-trace-proxy
